env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: module
  project: 
    - "tsconfig.json"
plugins:
  - '@typescript-eslint'
rules:
  indent: 
    - off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  require-await: off
  no-unused-vars: off
  "@typescript-eslint/explicit-function-return-type": 
    - error
    - allowExpressions: true
  "@typescript-eslint/no-unused-vars": error
  "@typescript-eslint/prefer-optional-chain": error
  "@typescript-eslint/no-explicit-any": error
  "@typescript-eslint/no-redundant-type-constituents": error
  "@typescript-eslint/no-throw-literal": error
  "@typescript-eslint/prefer-as-const": error
  "@typescript-eslint/require-await": error
  "@typescript-eslint/switch-exhaustiveness-check": warn
  "@typescript-eslint/consistent-type-definitions": 
    - error
    - type
