export enum CommandNames {
	ADD = "add",
	COURSES = "courses",
	JOIN = "join",
	KICK = "kick",
	LEAVE = "leave",
	PERIOD = "period",
	PING = "ping",
	VERIFY = "verify",
	BUTTONS = "buttons",
	MOTTAGNINGSMODE = "mottagningsmode",
	COMMUNITY = "community",
	TRANSLATE_MSG = "Translate to English",
	CLUB = "club",
}
