export enum CommandNames {
	COURSES = "courses",
	JOIN = "join",
	MESSAGE = "message",
	LEAVE = "leave",
	PERIOD = "period",
	VERIFY = "verify",
	BUTTONS = "buttons",
	COMMUNITY = "community",
	TRANSLATE_MSG = "Translate to English",
	CLUB = "club",
	KTHID = "kthid",
	NOLLEGRUPP = "nollegrupp",
	DFUNK = "dfunk",
	KILLMOTTAGNINGEN = "killmottagningen",
	MOTTAGNINGEN = "mottagningen",
	TEST = "test",
}
