name: Deploy

on:
  # Can be activated manually
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Push to medusa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      # https://stackoverflow.com/a/2462357/16911837
      run: |
        chmod +x ./deploy.sh
        ./deploy.sh
