name: Deploy

on:
  # Can only be activated manually
  workflow_dispatch:

jobs:
  # Test that it builds
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # https://github.com/marketplace/actions/dokku-deploy-action?version=v1
    - name: Deploy on medusa
      uses: idoberko2/dokku-deploy-github-action@v1
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
        dokku-user: 'dokku'
        remote-branch: 'master'
        dokku-host: 'medusa.datasektionen.se'
        app-name: 'harmony'
